[package]
name = "neli"
version = "0.1.2"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = "Type safe netlink library written in Rust"
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/neli"
keywords = ["netlink"]
include = [
    "**/*.rs",
    "**/*.c",
    "Cargo.toml",
    "LICENSE",
]

[build-dependencies]
cc = "1.0"

[dependencies]
byteorder = "1"
libc = "0.2"
